from pydantic_settings import BaseSettings
import os

class Settings(BaseSettings):
    logging_dir: str = "logs"
    models_dir: str = "models"
    assets_logo: str = "assets/logo.png"
    random_state: int = 42
    default_cv: int = 5
    default_fprob: float = 0.99
    leverage_factor: float = 5.0
    mahalanobis_factor: float = 3.0
    n_components_default: int = 5
    modo_padrao: str = "regressao"
    plsr_dir: str = os.path.join("models", "plsr")
    plsda_dir: str = os.path.join("models", "plsda")

settings = Settings()

# Centralize the path where metrics generated by the training
# process are stored. Components that need to read or write the
# metrics file should import this constant rather than building
# the path themselves.
METRICS_FILE = os.path.join(settings.models_dir, 'metrics.json')
